// Copyright 2023-2024 SGLang Team
// Licensed under the Apache License, Version 2.0

//! `Req` — per-request scheduler state.
//!
//! This is the most heavily mutated object in `schedule_batch.py`'s `Req`
//! class (it tracks every bit of bookkeeping for a single request's life
//! cycle).  The Rust mirror here covers the **scheduler-visible** state
//! — fields that the queue, batch builder, and output processor touch.
//! Stream / detokenization state lives in the frontend crate.

use crate::radix_cache::NodeId;
use crate::types::sampling::SamplingParams;

/// Why a request finished, when it has finished.  Mirrors the
/// `Finish*` classes in `schedule_batch.py`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FinishReason {
    /// Hit `sampling_params.max_new_tokens`.
    Length { length: u32 },
    /// Stop-token match.
    MatchedToken { token_id: i64 },
    /// Stop-string match (post-detokenisation).
    MatchedStr { stop: String },
    /// Aborted by user / abort RPC.
    Aborted { message: String },
    /// Aborted by retraction policy under memory pressure.
    Retracted,
    /// Internal error (OOM at the last allocation slot, grammar error, …).
    Internal { message: String },
}

#[derive(Debug, Clone)]
pub struct Req {
    /// Stable request id, set by the frontend.
    pub rid: String,

    /// Tokenised prompt — the prefill input.  Stays immutable after
    /// admission.
    pub origin_input_ids: Vec<i32>,

    /// Tokens generated by the worker so far.  Grows by 1 per decode
    /// step until `finished_reason` is set.
    pub output_ids: Vec<i32>,

    pub sampling_params: SamplingParams,

    /// Position in the scheduler's `ReqToTokenPool`.  `None` once
    /// `release_kv_cache` has run.
    pub req_pool_idx: Option<u32>,

    /// Length of the prefix already cached in the radix tree at admission.
    /// Bytes 0..cache_protected_len of `req_to_token[req_pool_idx]` are
    /// guaranteed valid and reference-counted by the radix cache.
    pub cache_protected_len: u32,

    /// Total tokens the GPU side has actually allocated KV for —
    /// `prefix + output_ids.len()` once decoding starts.
    pub kv_allocated_len: u32,

    /// Tokens whose KV has been committed (radix-cache eligible).
    /// In non-spec decode this equals `kv_allocated_len`.
    pub kv_committed_len: u32,

    /// `release_kv_cache` already popped the committed range.  Defends
    /// against double-release from speculative-admission paths (see the
    /// long thread in `tp_worker_client.py` and the matching guard in
    /// `_handle_finished_req`).
    pub kv_committed_freed: bool,
    pub kv_overallocated_freed: bool,

    /// Set once `check_finished` decides the request is done.
    pub finished_reason: Option<FinishReason>,

    /// Pending finish reason injected by the abort path; consumed on the
    /// next `check_finished`.  Mirrors `Req.to_finish` in
    /// `schedule_batch.py`.
    pub to_finish: Option<FinishReason>,

    /// True after retraction; the req re-enters the waiting queue.
    pub is_retracted: bool,

    /// Radix-cache node this req has locked via `inc_lock_ref`.  The
    /// matching `dec_lock_ref` runs in the output processor when the
    /// req finishes (or gets retracted).  `None` means either the req
    /// hasn't been admitted yet or the prefix was empty.
    pub cached_node: Option<NodeId>,

    /// Length of the prefix the req imported from the radix cache at
    /// admission time.  Stored separately from `cache_protected_len`
    /// so the output processor can re-insert the *new* tokens (i.e.
    /// excluding the imported prefix) when the req finishes.
    pub prefix_len_from_cache: u32,

    /// Per-req flag mirroring Python's `TokenizedGenerateReqInput.
    /// return_hidden_states`.  The batch-level
    /// `to_model_worker_batch_payload` OR's these across the running
    /// reqs to choose `CaptureHiddenMode::Full` vs `Null` (see
    /// `schedule_batch.py:2607`).
    pub return_hidden_states: bool,

    /// How many of `output_ids` have already been pushed into a
    /// `BatchTokenIDOutput` frame.  Mirrors Python `Req.send_token_offset`.
    /// The next emit sends `output_ids_through_stop[send_token_offset..]`
    /// — this is what lets a single frame carry several accumulated
    /// tokens at finish time, even though the steady-state stream sends
    /// one token per iter.  Without it, a finish-iter that wraps the
    /// final sampled token AND any held-back tokens would drop the
    /// held-back ones (the bug Python's `output_ids_through_stop`
    /// machinery is there to prevent).
    pub send_token_offset: u32,

    /// Set true once the finish-frame for this req has been emitted.
    /// Mirrors Python `Req.finished_output`.  Guards against a second
    /// emit when the same req appears in the batch on the iter after
    /// it finished (defensive — the synchronous Rust loop filters
    /// finished reqs before the next batch, but the flag costs nothing
    /// and matches Python's invariant).
    pub finished_output: bool,

    /// Cutoff for `output_ids_through_stop` — `output_ids[..finished_len]`.
    /// Set by `check_finished` to:
    ///   * `output_ids.len()` for length / abort / retracted finishes
    ///     (every emitted token is real),
    ///   * `matched_pos + 1` for stop-token matches (so the EOS token
    ///     itself is included in the slice; the detokenizer trims it).
    /// `None` while the req is still running.
    pub finished_len: Option<u32>,
}

impl Req {
    pub fn new(rid: String, origin_input_ids: Vec<i32>, sampling_params: SamplingParams) -> Self {
        Self {
            rid,
            origin_input_ids,
            output_ids: Vec::new(),
            sampling_params,
            req_pool_idx: None,
            cache_protected_len: 0,
            kv_allocated_len: 0,
            kv_committed_len: 0,
            kv_committed_freed: false,
            kv_overallocated_freed: false,
            finished_reason: None,
            to_finish: None,
            is_retracted: false,
            cached_node: None,
            prefix_len_from_cache: 0,
            return_hidden_states: false,
            send_token_offset: 0,
            finished_output: false,
            finished_len: None,
        }
    }

    /// Mirror of Python `Req.output_ids_through_stop`: every output id
    /// up to and including the stop position (if any), otherwise the
    /// raw `output_ids`.  Used to build the per-frame token slice the
    /// detokenizer ultimately trims and decodes.
    pub fn output_ids_through_stop(&self) -> &[i32] {
        match self.finished_len {
            Some(n) => {
                let n = (n as usize).min(self.output_ids.len());
                &self.output_ids[..n]
            }
            None => &self.output_ids,
        }
    }

    pub fn finished(&self) -> bool {
        self.finished_reason.is_some()
    }

    /// Mirror of `Req.check_finished` in `schedule_batch.py`.  Only the
    /// length and stop-token checks are implemented here; string-based
    /// stops belong on the detokenizer side anyway.
    ///
    /// Returns the new finish reason if this call decided the req is done.
    pub fn check_finished(&mut self) -> Option<&FinishReason> {
        if self.finished_reason.is_some() {
            return self.finished_reason.as_ref();
        }
        if let Some(reason) = self.to_finish.take() {
            self.finished_reason = Some(reason);
            // Abort / retraction: every token already in output_ids
            // counts as "real" (no stop position to trim).
            if self.finished_len.is_none() {
                self.finished_len = Some(self.output_ids.len() as u32);
            }
            return self.finished_reason.as_ref();
        }
        if self.output_ids.len() >= self.sampling_params.max_new_tokens as usize {
            self.finished_reason = Some(FinishReason::Length {
                length: self.sampling_params.max_new_tokens,
            });
            self.finished_len = Some(self.sampling_params.max_new_tokens);
            return self.finished_reason.as_ref();
        }
        if let Some(stop_ids) = &self.sampling_params.stop_token_ids {
            if let Some(&last) = self.output_ids.last() {
                if stop_ids.contains(&last) && !self.sampling_params.no_stop_trim {
                    self.finished_reason = Some(FinishReason::MatchedToken {
                        token_id: last as i64,
                    });
                    // Include the stop token itself — mirror Python's
                    // `finished_len = matched_pos + 1`.  The detokenizer
                    // strips it via `trim_matched_stop_ids` when the
                    // finish reason has an integer `matched` field.
                    self.finished_len = Some(self.output_ids.len() as u32);
                    return self.finished_reason.as_ref();
                }
            }
        }
        None
    }

    /// Reset the bookkeeping bits that `retract_decode` clears.  Mirrors
    /// `Req.reset_for_retract` in `schedule_batch.py`.
    pub fn reset_for_retract(&mut self) {
        self.cache_protected_len = 0;
        self.kv_allocated_len = 0;
        self.kv_committed_len = 0;
        self.kv_committed_freed = false;
        self.kv_overallocated_freed = false;
        self.is_retracted = true;
        // The radix-cache lock should already have been released by
        // the caller (see `retract_decode`).  Forget the node so a
        // re-prefill picks a fresh one.
        self.cached_node = None;
        self.prefix_len_from_cache = 0;
        // Retracted reqs are not `finished` — they go back into the
        // waiting queue for a re-prefill.  Don't clear `output_ids`
        // here: the resumed prefill needs them to rebuild the prompt
        // continuation.  Also keep `send_token_offset` so any tokens
        // we already streamed aren't re-emitted on resume.
    }
}
