import unittest
from types import SimpleNamespace
from unittest.mock import MagicMock

import torch

from sglang.srt.managers.hisparse_coordinator import HiSparseCoordinator
from sglang.srt.mem_cache.allocator.hisparse import (
    DeepSeekV4HiSparseTokenToKVPoolAllocator,
    _HiSparsePageOwnership,
)
from sglang.test.ci.ci_register import register_cpu_ci

register_cpu_ci(est_time=1, suite="base-a-test-cpu")


class _PhysicalPageAllocator:
    def __init__(self, *, page_size: int = 16, num_pages: int = 8) -> None:
        self.page_size = page_size
        self.size = page_size * num_pages
        self.is_not_in_free_group = True
        self.free_pages = list(range(1, num_pages + 1))
        self.release_pages = []
        self.used_pages: set[int] = set()

    def alloc(self, need_size: int) -> torch.Tensor | None:
        num_pages = need_size // self.page_size
        if need_size % self.page_size or num_pages > len(self.free_pages):
            return None
        pages = self.free_pages[:num_pages]
        del self.free_pages[:num_pages]
        self.used_pages.update(pages)
        offsets = torch.arange(self.page_size, dtype=torch.int64)
        return (torch.tensor(pages)[:, None] * self.page_size + offsets).reshape(-1)

    def free(self, indices: torch.Tensor) -> None:
        for page in torch.unique(indices // self.page_size).tolist():
            if page not in self.used_pages:
                raise RuntimeError(f"double free of page {page}")
            self.used_pages.remove(page)
            self.free_pages.append(page)


def _make_dsv4_transaction():
    c4_page_size = 16
    compress_ratio = 4
    full_page_size = c4_page_size * compress_ratio
    physical = _PhysicalPageAllocator(page_size=c4_page_size)
    mapping = torch.zeros(256, dtype=torch.int64)

    allocator = object.__new__(DeepSeekV4HiSparseTokenToKVPoolAllocator)
    allocator.compress_ratio = compress_ratio
    allocator.page_size = full_page_size
    allocator.hisparse_page_size = c4_page_size
    allocator.hisparse_attn_allocator = physical
    allocator.full_to_hisparse_device_index_mapping = mapping
    allocator._page_ownership = _HiSparsePageOwnership(
        mapping=mapping, child_allocator=physical, page_size=c4_page_size
    )

    # A non-page-aligned 70-token prompt has 17 C4 values. C4 position 16 is
    # already durable in the PD host row; positions 17..31 are generated by
    # later EAGLE rounds. Reserve=12 may also allocate positions 32..47 before
    # position 31 commits, and that future page must remain live.
    logical_base = 256
    req_to_token = torch.arange(logical_base, logical_base + 192).unsqueeze(0)
    current_page = physical.alloc(c4_page_size)
    committed_page = physical.alloc(c4_page_size)
    future_page = physical.alloc(c4_page_size)
    # The direct-PD prefix has no device mapping. Paged extend fills the rest
    # of that request-local partial page from allocator page zero (slots 1..15).
    # The next two C4 pages use ordinary allocated physical pages.
    mapping[64 + 17 : 64 + 32] = current_page[1:]
    mapping[64 + 32 : 64 + 48] = committed_page
    mapping[64 + 48 : 64 + 64] = future_page

    owner = object.__new__(HiSparseCoordinator)
    owner.is_dsv4_hisparse = True
    owner._device_slot_owner = owner
    owner.compress_ratio = compress_ratio
    owner.page_size = c4_page_size
    owner.device = "cpu"
    owner.token_to_kv_pool_allocator = allocator
    owner.mem_pool_device = SimpleNamespace(
        translate_loc_from_full_to_compressed=lambda locs: locs[
            (locs + 1) % compress_ratio == 0
        ]
        // compress_ratio
    )
    owner.req_to_token_pool = SimpleNamespace(req_to_token=req_to_token)
    owner.req_to_host_pool = torch.arange(256, 448, dtype=torch.int64).unsqueeze(0)
    owner._req_c4_retired_len = {0: 16}
    owner._req_c4_written_len = {0: 17}
    owner._backup_device_locs_to_host = MagicMock()
    owner._is_resident = MagicMock(return_value=False)

    mirror = object.__new__(HiSparseCoordinator)
    mirror.is_dsv4_hisparse = True
    mirror._device_slot_owner = owner
    mirror._req_c4_retired_len = {0: 16}
    mirror._req_c4_written_len = {0: 17}
    mirror._validate_mirror_device_locs = MagicMock()
    mirror._backup_device_locs_to_host = MagicMock()

    req = SimpleNamespace(
        rid="non-aligned-prefill",
        req_pool_idx=0,
        origin_input_ids=list(range(70)),
        kv_committed_len=127,
        kv=SimpleNamespace(kv_allocated_len=256),
    )
    return (
        owner,
        mirror,
        req,
        physical,
        mapping,
        current_page,
        committed_page,
        future_page,
    )


class TestDSV4HiSparseDecodeTransaction(unittest.TestCase):
    def test_retires_only_complete_committed_c4_pages(self) -> None:
        (
            owner,
            mirror,
            req,
            physical,
            mapping,
            current_page,
            committed_page,
            future_page,
        ) = _make_dsv4_transaction()

        # The 16-slot C4 page is still partial at 127 committed full tokens.
        owner.retire_committed_dsv4_pages([req], mirror)
        owner._backup_device_locs_to_host.assert_not_called()
        mirror._backup_device_locs_to_host.assert_not_called()
        self.assertEqual(physical.used_pages, {1, 2, 3})
        self.assertEqual(owner._req_c4_retired_len[0], 16)

        # The next committed token closes the page. The prompt-owned first C4
        # slot remains untouched in host memory; the 15 generated slots are
        # backed up in both physical pools before the page is returned.
        req.kv_committed_len = 128
        owner.retire_committed_dsv4_pages([req], mirror)

        expected_host = owner.req_to_host_pool[0, 17:32]
        torch.testing.assert_close(
            owner._backup_device_locs_to_host.call_args.args[0], expected_host
        )
        torch.testing.assert_close(
            owner._backup_device_locs_to_host.call_args.args[1], current_page[1:]
        )
        torch.testing.assert_close(
            mirror._backup_device_locs_to_host.call_args.args[0], expected_host
        )
        torch.testing.assert_close(
            mirror._backup_device_locs_to_host.call_args.args[1], current_page[1:]
        )
        self.assertTrue(torch.all(mapping[64 + 17 : 64 + 32] == 0))
        torch.testing.assert_close(mapping[64 + 32 : 64 + 48], committed_page)
        torch.testing.assert_close(mapping[64 + 48 : 64 + 64], future_page)
        self.assertEqual(physical.used_pages, {2, 3})
        self.assertEqual(owner._req_c4_retired_len[0], 32)
        self.assertEqual(mirror._req_c4_retired_len[0], 32)

        # A later round commits the first ordinary physical page. Both payloads
        # become durable before the target clears its aliases and releases it.
        req.kv_committed_len = 192
        owner.retire_committed_dsv4_pages([req], mirror)
        torch.testing.assert_close(
            owner._backup_device_locs_to_host.call_args.args[1], committed_page
        )
        torch.testing.assert_close(
            mirror._backup_device_locs_to_host.call_args.args[1], committed_page
        )
        self.assertTrue(torch.all(mapping[64 + 32 : 64 + 48] == 0))
        torch.testing.assert_close(mapping[64 + 48 : 64 + 64], future_page)
        self.assertEqual(physical.used_pages, {3})
        self.assertEqual(owner._req_c4_retired_len[0], 48)

        # Re-entering at the same committed length is idempotent.
        owner.retire_committed_dsv4_pages([req], mirror)
        self.assertEqual(owner._backup_device_locs_to_host.call_count, 2)
        self.assertEqual(physical.free_pages.count(1), 1)

    def test_rejects_physical_page_alias_in_future_reserve(self) -> None:
        owner, mirror, req, physical, mapping, _, committed_page, _ = (
            _make_dsv4_transaction()
        )
        # Corrupt the reserve so a future logical position aliases the page
        # about to retire. Fail before backup/free instead of creating UAF.
        mapping[64 + 56] = committed_page[2]
        req.kv_committed_len = 192

        with self.assertRaisesRegex(RuntimeError, "uncommitted alias"):
            owner.retire_committed_dsv4_pages([req], mirror)

        owner._backup_device_locs_to_host.assert_not_called()
        mirror._backup_device_locs_to_host.assert_not_called()
        self.assertEqual(physical.used_pages, {1, 2, 3})
        self.assertEqual(owner._req_c4_retired_len[0], 16)


if __name__ == "__main__":
    unittest.main()
