python debug_no_server.py \
  --model deepseek-ai/DeepSeek-V3.2-Exp \
  --tp 1 --dp 1 --enable-dp-attention \
  --moe-runner-backend asym_comp \
  --json-model-override-args '{"num_hidden_layers": 5}' \
  --context-length 8192 \
  --max-total-tokens 8192 \
  --nccl-port 29500 \
  --chunked-prefill-size 2048 \
  --mem-fraction-static 0.90 \
  --moe-expert-offload cpu